# -*- coding: utf-8 -*-
"""Jogo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/thaf7/d2423d56a34928b2e8bb941b0af97837/untitled6.ipynb
"""

import random

numero = random.randint(1, 100)
tentativas = 0

print('Bem vindo ao jogo da adivinhação!')
print('Eu escolhi um numero entre entre 0 e 100. você tem 10 tentativas para advinhar')

while tentativas < 10:
  palpite = int(input('Digite o seu palpite:'))
  tentativas += 1
  if palpite == numero:
    print(f'Parabens! você acertou o numero em {tentativas} tentativas.')
    break
  elif palpite < numero:
    print('O numero e maior, Tente novamnete.')
  else:
    print('O numero e menor, Tente novamnete.')
else :
   print(f'Voce perdeu o numero era {numero}')